npmScopes:
  coscene-io:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAuthToken: ${GH_PACKAGES_ORG_TOKEN}
  buf:
    npmRegistryServer: "https://npm.buf.build"
    npmAuthToken: ${BUF_TOKEN}
