changesetBaseRefs:
  - main
  - origin/main

defaultSemverRangePrefix: ""

nodeLinker: node-modules

npmScopes:
  buf:
    npmAuthToken: "${BUF_BUILD_TOKEN}"
    npmRegistryServer: "https://buf.build/gen/npm/v1/"
  coscene-io:
    npmAuthToken: "${GH_PACKAGES_ORG_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"
patchFolder: ./patches

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"

yarnPath: .yarn/yarn-wrapper.js
