# since skaffold v2.0.3
apiVersion: skaffold/v4beta1
kind: Config
build:
  tagPolicy:
    # e.g: 2022-12-05_v22.48.0-8-g295c572a
    # e.g: 2022-12-05-78c7d2b
    customTemplate:
      template: "{{.FOO}}-{{.BAR}}"
      components:
        - name: FOO
          dateTime:
            format: "2006-01-02"
            timezone: "UTC"
        - name: BAR
          gitCommit:
            ignoreChanges: true
  artifacts:
    - image: coseus.azurecr.io/honeybee
      context: .
      custom:
        buildCommand: docker buildx build --build-arg BUF_BUILD_TOKEN={{.BUF_BUILD_TOKEN}} --build-arg SENTRY_AUTH_TOKEN={{.SENTRY_AUTH_TOKEN}} --build-arg GH_PACKAGES_ORG_TOKEN={{.GH_PACKAGES_ORG_TOKEN}} --build-arg CURRENT_IMAGE_TAG=$IMAGE --push --tag $IMAGE $BUILD_CONTEXT

  local:
    useBuildkit: true
profiles:
  - name: local
    build:
      local:
        push: false
        useBuildkit: false
        tryImportMissing: false
  - name: azure-dev-east-us
    build:
      local:
        useBuildkit: true
