apiVersion: skaffold/v2beta28
kind: Config
build:
  tagPolicy:
    # e.g: 2022-12-05_v22.48.0-8-g295c572a
    # e.g: 2022-12-05-78c7d2b
    customTemplate:
      template: "{{.FOO}}-{{.BAR}}"
      components:
        - name: FOO
          dateTime:
            format: "2006-01-02"
            timezone: "UTC"
        - name: BAR
          gitCommit:
            ignoreChanges: true
  artifacts:
    - image: registry.cn-hangzhou.aliyuncs.com/coscene/honeybee
      custom:
        buildCommand: docker buildx build --build-arg HTTP_PROXY=http://gfw:7890 --build-arg HTTPS_PROXY=http://gfw:7890 --build-arg http_proxy=http://gfw:7890 --build-arg https_proxy=http://gfw:7890 --build-arg BUF_TOKEN={{.BUF_TOKEN}} --build-arg GH_PACKAGES_ORG_TOKEN={{.GH_PACKAGES_ORG_TOKEN}} --build-arg PROJECT_ENV=production --file Dockerfile --tag $IMAGE --push $BUILD_CONTEXT
        dependencies:
          paths:
          - .
  local:
    useBuildkit: true
    tryImportMissing: true

profiles:
  - name: azure-dev-east-us
    build:
      artifacts:
        - image: coseus.azurecr.io/honeybee
          context: .
          docker:
            dockerfile: Dockerfile
            buildArgs:
              BUF_TOKEN: "{{.BUF_TOKEN}}"
              GH_PACKAGES_ORG_TOKEN: "{{.GH_PACKAGES_ORG_TOKEN}}"
              PROJECT_ENV: "azureDev"
  - name: aliyun-staging-cn-hangzhou
