// SPDX-FileCopyrightText: Copyright (C) 2022-2024 Shanghai coScene Information Technology Co., Ltd.<hi@coscene.io>
// SPDX-License-Identifier: MPL-2.0

// This Source Code Form is subject to the terms of the Mozilla Public
// License, v2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/

export enum Endpoint {
  AuthorizeDevice = "coscene.dataplatform.v1alpha2.services.DeviceService.AuthorizeDevice",
  BatchStatOnlineDevice = "coscene.dataplatform.v1alpha2.services.DeviceService.BatchStatOnlineDevice",
  CreateDevice = "coscene.dataplatform.v1alpha2.services.DeviceService.CreateDevice",
  DeleteDevice = "coscene.dataplatform.v1alpha2.services.DeviceService.DeleteDevice",
  GetDevice = "coscene.dataplatform.v1alpha2.services.DeviceService.GetDevice",
  ListDevices = "coscene.dataplatform.v1alpha2.services.DeviceService.ListDevices",
  RevokeDevice = "coscene.dataplatform.v1alpha2.services.DeviceService.RevokeDevice",
  StatOnlineDevice = "coscene.dataplatform.v1alpha2.services.DeviceService.StatOnlineDevice",
  UpdateDevice = "coscene.dataplatform.v1alpha2.services.DeviceService.UpdateDevice",

  ListRevisions = "coscene.dataplatform.v1alpha2.services.RevisionService.ListRevisions",
  GetRevision = "coscene.dataplatform.v1alpha2.services.RevisionService.GetRevision",
  GenerateRevision = "coscene.dataplatform.v1alpha2.services.RevisionService.GenerateRevision",

  AssignOrganizationRole = "coscene.dataplatform.v1alpha1.services.RoleService.AssignOrganizationRole",
  AssignProjectRole = "coscene.dataplatform.v1alpha1.services.RoleService.AssignProjectRole",
  AssignWarehouseRole = "coscene.dataplatform.v1alpha1.services.RoleService.AssignWarehouseRole",
  BatchAssignProjectRole = "coscene.dataplatform.v1alpha1.services.RoleService.BatchAssignProjectRole",
  BatchGetTeamRoles = "coscene.dataplatform.v1alpha1.services.RoleService.BatchGetTeamRoles",
  BatchGetUserRoles = "coscene.dataplatform.v1alpha1.services.RoleService.BatchGetUserRoles",
  ChangeProjectVisibility = "coscene.dataplatform.v1alpha1.services.ProjectService.ChangeProjectVisibility",
  CreateRole = "coscene.dataplatform.v1alpha1.services.RoleService.CreateRole",
  GetRole = "coscene.dataplatform.v1alpha1.services.RoleService.GetRole",
  ListRoles = "coscene.dataplatform.v1alpha1.services.RoleService.ListRoles",
  UnassignedOrganizationRole = "coscene.dataplatform.v1alpha1.services.RoleService.UnassignedOrganizationRole",
  UnassignedProjectRole = "coscene.dataplatform.v1alpha1.services.RoleService.UnassignedProjectRole",
  UnassignedWarehouseRole = "coscene.dataplatform.v1alpha1.services.RoleService.UnassignedWarehouseRole",
  UpdateRole = "coscene.dataplatform.v1alpha1.services.RoleService.UpdateRole",

  BatchGetUsers = "coscene.dataplatform.v1alpha1.services.UserService.BatchGetUsers",
  CreateUser = "coscene.dataplatform.v1alpha1.services.UserService.CreateUser",
  DeleteUser = "coscene.dataplatform.v1alpha2.services.UserService.DeleteUser",
  DisableUser = "coscene.dataplatform.v1alpha2.services.UserService.DisableUser",
  EnableUser = "coscene.dataplatform.v1alpha2.services.UserService.EnableUser",
  GenerateAvatarUploadUrl = "coscene.dataplatform.v1alpha2.services.UserService.GenerateAvatarUploadUrl",
  GenerateResetPasswordToken = "coscene.dataplatform.v1alpha2.services.UserService.GenerateResetPasswordToken",
  GetUser = "coscene.dataplatform.v1alpha1.services.UserService.GetUser",
  ImportUser = "coscene.dataplatform.v1alpha2.services.UserService.ImportUser",
  ListOrganizationUsers = "coscene.dataplatform.v1alpha1.services.UserService.ListOrganizationUsers",
  ListProjectExcludedUsers = "coscene.dataplatform.v1alpha1.services.UserService.ListProjectExcludedUsers",
  ListProjectUsers = "coscene.dataplatform.v1alpha1.services.UserService.ListProjectUsers",
  ListTeamUsers = "coscene.dataplatform.v1alpha1.services.UserService.ListTeamUsers",
  ListUsers = "coscene.dataplatform.v1alpha1.services.UserService.ListUsers",
  ModifyPassword = "coscene.dataplatform.v1alpha2.services.UserService.ModifyPassword",
  ResetPassword = "coscene.dataplatform.v1alpha2.services.UserService.ResetPassword",
  UpdateUser = "coscene.dataplatform.v1alpha2.services.UserService.UpdateUser",
  AcceptInvitation = "coscene.dataplatform.v1alpha2.services.UserService.AcceptInvitation",
  InviteOrganizationUser = "coscene.dataplatform.v1alpha2.services.UserService.InviteOrganizationUser",

  ListTags = "coscene.dataplatform.v1alpha2.services.TagService.ListTags",
  GetTag = "coscene.dataplatform.v1alpha2.services.TagService.GetTag",
  CreateTag = "coscene.dataplatform.v1alpha2.services.TagService.CreateTag",
  DeleteTag = "coscene.dataplatform.v1alpha2.services.TagService.DeleteTag",

  AddOrganizationUser = "coscene.dataplatform.v1alpha1.services.OrganizationService.AddOrganizationUser",
  CreateOrganization = "coscene.dataplatform.v1alpha1.services.OrganizationService.CreateOrganization",
  GetOrganization = "coscene.dataplatform.v1alpha1.services.OrganizationService.GetOrganization",
  ListOrganizations = "coscene.dataplatform.v1alpha1.services.OrganizationService.ListOrganizations",
  ListUserOrganizations = "coscene.dataplatform.v1alpha1.services.OrganizationService.ListUserOrganizations",
  RemoveOrganizationUser = "coscene.dataplatform.v1alpha1.services.OrganizationService.RemoveOrganizationUser",
  StatOrganization = "coscene.dataplatform.v1alpha1.services.OrganizationService.StatOrganization",
  UpdateOrganization = "coscene.dataplatform.v1alpha1.services.OrganizationService.UpdateOrganization",

  ListActivities = "coscene.dataplatform.v1alpha1.services.ActivityService.ListActivities",

  BatchGenerateUploadUrls = "coscene.dataplatform.v1alpha2.services.BlobService.BatchGenerateUploadUrls",
  BatchGetBlobs = "coscene.dataplatform.v1alpha2.services.BlobService.BatchGetBlobs",
  DeleteBlob = "coscene.dataplatform.v1alpha2.services.BlobService.DeleteBlob",
  GenerateDownloadUrl = "coscene.dataplatform.v1alpha2.services.BlobService.GenerateDownloadUrl",
  GenerateUploadUrl = "coscene.dataplatform.v1alpha2.services.BlobService.GenerateUploadUrl",
  GetBlob = "coscene.dataplatform.v1alpha2.services.BlobService.GetBlob",
  RefreshBlobMedia = "coscene.dataplatform.v1alpha2.services.BlobService.RefreshBlobMedia",
  UpdateBlob = "coscene.dataplatform.v1alpha2.services.BlobService.UpdateBlob",

  CreateWarehouse = "coscene.dataplatform.v1alpha1.services.WarehouseService.CreateWarehouse",
  GetWarehouse = "coscene.dataplatform.v1alpha1.services.WarehouseService.GetWarehouse",
  ListWarehouses = "coscene.dataplatform.v1alpha1.services.WarehouseService.ListWarehouses",
  UpdateWarehouse = "coscene.dataplatform.v1alpha1.services.WarehouseService.UpdateWarehouse",
  VerifyWarehouseSlug = "coscene.dataplatform.v1alpha1.services.WarehouseService.VerifyWarehouseSlug",

  AddTeamUser = "coscene.dataplatform.v1alpha1.services.TeamService.AddTeamUser",
  CreateTeam = "coscene.dataplatform.v1alpha1.services.TeamService.CreateTeam",
  GetTeam = "coscene.dataplatform.v1alpha1.services.TeamService.GetTeam",
  ListTeams = "coscene.dataplatform.v1alpha1.services.TeamService.ListTeams",
  RemoveTeamUser = "coscene.dataplatform.v1alpha1.services.TeamService.RemoveTeamUser",
  UpdateTeam = "coscene.dataplatform.v1alpha1.services.TeamService.UpdateTeam",

  ArchiveProject = "coscene.dataplatform.v1alpha1.services.ProjectService.ArchiveProject",
  BindDevices = "coscene.dataplatform.v1alpha1.services.ProjectService.BindDevices",
  CheckPermission = "coscene.dataplatform.v1alpha1.services.ProjectService.CheckPermission",
  ConvertProjectSlug = "coscene.dataplatform.v1alpha1.services.ProjectService.ConvertProjectSlug",
  CreateProject = "coscene.dataplatform.v1alpha1.services.ProjectService.CreateProject",
  CreateProjectUsingTemplate = "coscene.dataplatform.v1alpha1.services.ProjectService.CreateProjectUsingTemplate",
  DeleteProject = "coscene.dataplatform.v1alpha1.services.ProjectService.DeleteProject",
  GetProject = "coscene.dataplatform.v1alpha1.services.ProjectService.GetProject",
  InstallApplication = "coscene.dataplatform.v1alpha1.services.ProjectService.InstallApplication",
  ListDeviceProjects = "coscene.dataplatform.v1alpha1.services.ProjectService.ListDeviceProjects",
  ListProjects = "coscene.dataplatform.v1alpha1.services.ProjectService.ListProjects",
  ListProjectStages = "coscene.dataplatform.v1alpha1.services.ProjectService.ListProjectStages",
  ListStarredProjects = "coscene.dataplatform.v1alpha1.services.ProjectService.ListStarredProjects",
  ListUserProjects = "coscene.dataplatform.v1alpha1.services.ProjectService.ListUserProjects",
  StarProject = "coscene.dataplatform.v1alpha1.services.ProjectService.StarProject",
  StatProject = "coscene.dataplatform.v1alpha1.services.ProjectService.StatProject",
  TransmitScene = "coscene.dataplatform.v1alpha1.services.ProjectService.TransmitScene",
  UnarchiveProject = "coscene.dataplatform.v1alpha1.services.ProjectService.UnarchiveProject",
  UnbindDevices = "coscene.dataplatform.v1alpha1.services.ProjectService.UnbindDevices",
  UninstallApplication = "coscene.dataplatform.v1alpha1.services.ProjectService.UninstallApplication",
  UnstarProject = "coscene.dataplatform.v1alpha1.services.ProjectService.UnstarProject",
  UpdateProject = "coscene.dataplatform.v1alpha1.services.ProjectService.UpdateProject",
  VerifyProjectSlug = "coscene.dataplatform.v1alpha1.services.ProjectService.VerifyProjectSlug",
  ListPublicProjects = "coscene.dataplatform.v1alpha1.services.ProjectService.ListPublicProjects",
  GetPublicProject = "coscene.dataplatform.v1alpha1.services.ProjectService.GetPublicProject",
  GenerateProjectThumbnailUploadUrl = "coscene.dataplatform.v1alpha1.services.ProjectService.GenerateProjectThumbnailUploadUrl",
  CopyProject = "coscene.dataplatform.v1alpha1.services.ProjectService.CopyProject",

  ListEvents = "coscene.dataplatform.v1alpha2.services.EventService.ListEvents",
  GetEvent = "coscene.dataplatform.v1alpha2.services.EventService.GetEvent",
  CreateEvent = "coscene.dataplatform.v1alpha2.services.EventService.CreateEvent",
  DeleteEvent = "coscene.dataplatform.v1alpha2.services.EventService.DeleteEvent",
  UpdateEvent = "coscene.dataplatform.v1alpha2.services.EventService.UpdateEvent",

  CreateToken = "coscene.dataplatform.v1alpha1.services.TokenService.CreateToken",
  DeleteToken = "coscene.dataplatform.v1alpha1.services.TokenService.DeleteToken",
  ListTokens = "coscene.dataplatform.v1alpha1.services.TokenService.ListTokens",
  VerifyToken = "coscene.dataplatform.v1alpha1.services.TokenService.VerifyToken",

  CreateBasicCredential = "coscene.dataplatform.v1alpha2.services.ContainerRegistryService.CreateBasicCredential",
  ListImages = "coscene.dataplatform.v1alpha2.services.ContainerRegistryService.ListImages",
  ListImageTags = "coscene.dataplatform.v1alpha2.services.ContainerRegistryService.ListImageTags",

  // dataworkflow
  AggregateWorkflowRunArtifacts = "coscene.dataworkflow.v1alpha1.services.WorkflowRunService.AggregateWorkflowRunArtifacts",
  AggregateWorkflowRunLogs = "coscene.dataworkflow.v1alpha1.services.WorkflowRunService.AggregateWorkflowRunLogs",
  GenerateWorkflowRunArtifactDownloadUrl = "coscene.dataworkflow.v1alpha1.services.WorkflowRunService.GenerateWorkflowRunArtifactDownloadUrl",
  GetWorkflowRun = "coscene.dataworkflow.v1alpha1.services.WorkflowRunService.GetWorkflowRun",
  ListWorkflowRunRecords = "coscene.dataworkflow.v1alpha1.services.WorkflowRunService.ListWorkflowRunRecords",
  ListWorkflowRuns = "coscene.dataworkflow.v1alpha1.services.WorkflowRunService.ListWorkflowRuns",
  LogWorkflowRun = "coscene.dataworkflow.v1alpha1.services.WorkflowRunService.LogWorkflowRun",
  PreviewWorkflowRunEntryArtifacts = "coscene.dataworkflow.v1alpha1.services.WorkflowRunEntryService.PreviewWorkflowRunEntryArtifacts",
  RetryWorkflowRun = "coscene.dataworkflow.v1alpha1.services.WorkflowRunService.RetryWorkflowRun",
  TerminateWorkflowRun = "coscene.dataworkflow.v1alpha1.services.WorkflowRunService.TerminateWorkflowRun",

  AggregateWorkflowRunEntryArtifacts = "coscene.dataworkflow.v1alpha1.services.WorkflowRunEntryService.AggregateWorkflowRunEntryArtifacts",
  AggregateWorkflowRunEntryLogs = "coscene.dataworkflow.v1alpha1.services.WorkflowRunEntryService.AggregateWorkflowRunEntryLogs",
  GenerateWorkflowRunEntryArtifactDownloadUrl = "coscene.dataworkflow.v1alpha1.services.WorkflowRunEntryService.GenerateWorkflowRunEntryArtifactDownloadUrl",
  GetWorkflowRunEntry = "coscene.dataworkflow.v1alpha1.services.WorkflowRunEntryService.GetWorkflowRunEntry",
  ListWorkflowRunEntries = "coscene.dataworkflow.v1alpha1.services.WorkflowRunEntryService.ListWorkflowRunEntries",
  LogWorkflowRunEntry = "coscene.dataworkflow.v1alpha1.services.WorkflowRunEntryService.LogWorkflowRunEntry",
  RetryWorkflowRunEntry = "coscene.dataworkflow.v1alpha1.services.WorkflowRunService.RetryWorkflowRunEntry",
  TerminateWorkflowRunEntry = "coscene.dataworkflow.v1alpha1.services.WorkflowRunEntryService.TerminateWorkflowRunEntry",

  CreateTestBundle = "coscene.datamatrix.v1alpha1.services.TestBundleService.CreateTestBundle",
  GenerateBundleDownloadUrl = "coscene.datamatrix.v1alpha1.services.TestBundleService.GenerateBundleDownloadUrl",
  GenerateBundleUploadUrl = "coscene.datamatrix.v1alpha1.services.TestBundleService.GenerateUploadUrl",
  GetTestBundle = "coscene.datamatrix.v1alpha1.services.TestBundleService.GetTestBundle",
  ListCategories = "coscene.datamatrix.v1alpha1.services.TestBundleService.ListCategories",
  ListTestBundles = "coscene.datamatrix.v1alpha1.services.TestBundleService.ListTestBundles",
  UpdateTestBundle = "coscene.datamatrix.v1alpha1.services.TestBundleService.UpdateTestBundle",

  CreateTestCase = "coscene.datamatrix.v1alpha1.services.TestCaseService.CreateTestCase",
  GetTestCase = "coscene.datamatrix.v1alpha1.services.TestCaseService.GetTestCase",
  GetTestCaseHistoryMatrix = "coscene.datamatrix.v1alpha1.services.TestCaseService.GetTestCaseHistoryMatrix",
  ListTestCaseHistoryRecords = "coscene.datamatrix.v1alpha1.services.TestCaseService.ListTestCaseHistoryRecords",
  ListTestCases = "coscene.datamatrix.v1alpha1.services.TestCaseService.ListTestCases",
  TestCaseHistoryMatrix = "coscene.datamatrix.v1alpha1.services.TestCaseService.TestCaseHistoryMatrix",

  CreateTestSource = "coscene.datamatrix.v1alpha1.services.TestSourceService.CreateTestSource",
  GenerateTestSourceUploadUrl = "coscene.datamatrix.v1alpha1.services.TestSourceService.GenerateUploadUrl",
  GetTestSource = "coscene.datamatrix.v1alpha1.services.TestSourceService.GetTestSource",
  ListTestSources = "coscene.datamatrix.v1alpha1.services.TestSourceService.ListTestSources",
  UpdateTestSource = "coscene.datamatrix.v1alpha1.services.TestSourceService.UpdateTestSource",

  AggregateJobRunArtifacts = "coscene.matrix.v1alpha1.services.JobRunService.AggregateJobRunArtifacts",
  AggregateJobRunOutputs = "coscene.matrix.v1alpha1.services.JobRunService.AggregateJobRunOutputs",
  GenerateJobRunArtifactDownloadUrl = "coscene.matrix.v1alpha1.services.JobRunService.GenerateJobRunArtifactDownloadUrl",
  GenerateJobRunLogDownloadUrl = "coscene.matrix.v1alpha1.services.JobRunService.GenerateJobRunLogDownloadUrl",
  GenerateJobRunOutputDownloadUrl = "coscene.matrix.v1alpha1.services.JobRunService.GenerateJobRunOutputDownloadUrl",
  GetJobRun = "coscene.matrix.v1alpha1.services.JobRunService.GetJobRun",
  GetJobRunArtifacts = "coscene.matrix.v1alpha1.services.JobRunService.GetJobRunArtifacts",
  GetJobRunDag = "coscene.matrix.v1alpha1.services.JobRunService.GetJobRunDag",
  GetJobRunMetrics = "coscene.matrix.v1alpha1.services.JobRunService.GetJobRunMetrics",
  GetJobRunOutputs = "coscene.matrix.v1alpha1.services.JobRunService.GetJobRunOutputs",
  ListJobRuns = "coscene.matrix.v1alpha1.services.JobRunService.ListJobRuns",
  LogJobRun = "coscene.matrix.v1alpha1.services.JobRunService.LogJobRun",
  TerminateJobRun = "coscene.matrix.v1alpha1.services.JobRunService.TerminateJobRun",

  AggregateMatrixWorkflowRunArtifacts = "coscene.matrix.v1alpha1.services.WorkflowRunService.AggregateWorkflowRunArtifacts",
  AggregateMatrixWorkflowRunLogs = "coscene.matrix.v1alpha1.services.WorkflowRunService.AggregateWorkflowRunLogs",
  CreateMatrixWorkflowRun = "coscene.matrix.v1alpha1.services.WorkflowRunService.CreateWorkflowRun",
  GetMatrixWorkflowRun = "coscene.matrix.v1alpha1.services.WorkflowRunService.GetWorkflowRun",
  GetMatrixWorkflowRunReport = "coscene.matrix.v1alpha1.services.WorkflowRunService.GetWorkflowRunReport",
  ListMatrixWorkflowRuns = "coscene.matrix.v1alpha1.services.WorkflowRunService.ListWorkflowRuns",
  RetryMatrixWorkflowRun = "coscene.matrix.v1alpha1.services.WorkflowRunService.RetryWorkflowRun",
  TerminateMatrixWorkflowRun = "coscene.matrix.v1alpha1.services.WorkflowRunService.TerminateWorkflowRun",

  BatchCreateMatrixWorkflows = "coscene.matrix.v1alpha1.services.WorkflowService.BatchCreateWorkflows",
  PreviewTemplate = "coscene.matrix.v1alpha1.services.WorkflowService.PreviewTemplate",
  ListMatrixWorkflows = "coscene.matrix.v1alpha1.services.WorkflowService.ListWorkflows",
  UpdateMatrixWorkflow = "coscene.matrix.v1alpha1.services.WorkflowService.UpdateWorkflow",

  ListMatrixTestCaseHistoryRuns = "coscene.matrix.v1alpha1.services.TestCaseService.ListTestCaseHistoryRuns",
  ListMatrixTestCaseResults = "coscene.matrix.v1alpha1.services.TestCaseService.ListTestCaseResults",

  GetOrgConfigMap = "coscene.dataplatform.v1alpha2.services.ConfigMapService.GetConfigMap",
  ListConfigMaps = "coscene.dataplatform.v1alpha2.services.ConfigMapService.ListConfigMaps",
  UpsertOrgConfigMap = "coscene.dataplatform.v1alpha2.services.ConfigMapService.UpsertConfigMap",

  GetTicketSystem = "coscene.dataplatform.v1alpha2.services.TicketSystemService.GetTicketSystem",
  GetTicketSystemMetadata = "coscene.dataplatform.v1alpha2.services.TicketSystemService.GetTicketSystemMetadata",
  UpsertTicketSystem = "coscene.dataplatform.v1alpha2.services.TicketSystemService.UpsertTicketSystem",
}
