name: Deploy to azure-dev-east-us
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment: azure-dev-east-us
    env:
      GH_PACKAGES_ORG_TOKEN: ${{ secrets.GH_PACKAGES_ORG_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          lfs: true

      - name: Setup CD workspace
        uses: coscene-io/setup-cd-workspace-all-in-one@v0.0.7
        with:
          cloud-provider: Azure
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          acr-login-registry: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
          acr-username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          acr-password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
          azure-aks-resource-group: 'Dev-EUS'
          azure-aks-cluster-name: 'Dev-EUS'
          need-cd-tools: true

      - name: Skaffold build
        run: |
          skaffold build -p azure-dev-east-us -t latest

      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v1.1.0
        with:
          helmfile-version: "v0.148.1"
          helm-version: "v3.10.2"
          additional-helm-plugins: https://github.com/aslafy-z/helm-git --version 0.14.0

      - name: Helm add coScene repo
        env:
          REPOSITORY_TOKEN: ${{ secrets.GH_PACKAGES_ORG_TOKEN }}
        run: |
          helm repo add coscene git+https://$REPOSITORY_TOKEN@github.com/coscene-io/chart@\?ref=main
          helm repo update

      - name: Helm upgrade
        run: |
          helm upgrade -n coscene --reuse-values coscene coscene/coscene --set honeybee.rollout=$GITHUB_SHA
