# Since we cannot solve the problem of build failure on self-hosted runners
# we can only build the image on the GitHub runner,
# and then synchronize it to the Alibaba ACR service.
# And this is a way to save self-hosted runner resources.
name: Deploy to aliyun-keenon-cn-hangzhou

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04
    environment: azure-dev-east-us
    env:
      BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
      GH_PACKAGES_ORG_TOKEN: ${{ secrets.GH_PACKAGES_ORG_TOKEN }}
      ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          lfs: true

      - name: Setup CD workspace
        uses: coscene-io/setup-cd-workspace-all-in-one@v0.0.7
        with:
          cloud-provider: Azure
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          acr-login-registry: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
          acr-username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          acr-password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
          azure-aks-resource-group: "Dev-EUS"
          azure-aks-cluster-name: "Dev-EUS"
          need-cd-tools: true

      - name: Skaffold build
        run: |
          skaffold build -p aliyun-keenon-cn-hangzhou -t keenon-latest
  sync:
    runs-on: self-hosted
    needs: build
    environment: aliyun-keenon-cn-hangzhou
    steps:
      - name: Login to Azure Docker Registry
        uses: docker/login-action@v2
        with:
          registry: coseus.azurecr.io
          username: ${{ secrets.ACR_ADMIN_USERNAME }}
          password: ${{ secrets.ACR_ADMIN_PASSWORD }}
      - name: Login to AliCloud Docker Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        env:
          http_proxy: http://gfw:7890
          https_proxy: http://gfw:7890
        with:
          driver-opts: |
            env.http_proxy=${{ env.http_proxy }}
            env.https_proxy=${{ env.http_proxy }}
      - name: Push image to AliCloud
        env:
          SRC: coseus.azurecr.io/honeybee:keenon-latest
          DST: registry.cn-hangzhou.aliyuncs.com/coscene/honeybee:keenon-latest
        run: |
          docker pull $SRC
          docker tag $SRC $DST
          docker push $DST
          echo "mirror $SRC to $DST" >> $GITHUB_STEP_SUMMARY
