name: test cli

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "Version to publish (e.g., v1.0.0)"
        required: true
      environment:
        type: choice
        description: "publish studio to"
        required: true
        default: "saas"
        options:
          - dev
          - saas

jobs:
  set_cos_config_file:
    environment: ${{ github.event.inputs.environment }}
    runs-on: macos-latest
    steps:
      - name: Set cos config file
        id: set_cos_config_file
        run: |
          ls
          echo "${{ vars.APP_CONFIG }}" > packages/studio-desktop/src/public/cos-config.js
          cat packages/studio-desktop/src/public/cos-config.js
