name: test cli

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "The environment to test"
        required: true
        default: "dev"
        options:
          - dev
          - saas

jobs:
  test:
    environment: saas
    runs-on: ubuntu-latest
    steps:
      - name: echo APP_CONFIG
        id: echo_app_config
        run: |
          echo "APP_CONFIG: ${{ vars.APP_CONFIG }}"
