name: test cli

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "The environment to test"
        required: true
        default: "dev"
        options:
          - dev
          - sass

jobs:
  test:
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      # echo the APP_CONFIG environment variable
      # - run: echo "APP_CONFIG: ${{ env.APP_CONFIG }}"
      - name: echo APP_CONFIG
        id: echo_app_config
        run: |
          echo "APP_CONFIG: ${{ env.APP_CONFIG }}"
